name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        with:
          command: clean

      - run: cargo build --verbose
